### ISSUE TITLE
Seems to only support coffee script

### ISSUE THREAD

**Issue by awildeep** [kristianmandrup/ember-konacha-rails#1]
Your code seems to only support coffee script.  Any plans to support JS ERB templates as well (and perhaps an application setting to control the default behavior)?

**Comment by kristianmandrup** [comment]
@awildeep you are welcome to add any behaviour/functionality that you find is missing ;) Just send me a pull :) I never used JS ERB templates myself. The coffeescript can be compiled to javascript and saved as static js files ready for use.

**Comment by kristianmandrup** [comment]
Now I finally added support for generating javascript specs as well ;)
