### ISSUE TITLE
undefined before/ after hooks

### ISSUE THREAD

**Issue by yortz** [kristianmandrup/ember-konacha-rails#8]
Hi, I've installed the ember-konacha-rails gem in one of my apps, and when trying to run the tests (either via konacha or in the browser) it complains about undefined hooks in the spec_helper.

```
$ bundle exec rake konacha:run
FFFF

  Failed: undefined "before each" hook
    Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.

  Failed: undefined "after each" hook
    Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.

  Failed: undefined "before each" hook
    Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.

  Failed: undefined "after each" hook
    Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.

Finished in 0.00 seconds
4 examples, 2 failed, 0 pending
```

So I tried commenting out the hooks and the rake task gets executed (I can even run tests in the browser) but I got the following:

```
$ bundle exec rake konacha:run
.F

  Failed: App.Store works with latest Ember-Data revision
    AssertionError: expected undefined to equal 12

Finished in 0.00 seconds
2 examples, 1 failed, 0 pending
```

So it seems router test is passing while the store one is failing. Am I missing something? My setup is the following:

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.5.0 
DEBUG: Ember Data : 1.0.0-beta.7.f87cba88 
DEBUG: Handlebars : 1.3.0 
DEBUG: jQuery     : 1.11.0 
DEBUG: ------------------------------- 
```

I've currently defined Ember App.rootelement to be a div with id #ember-app inside my rails application layout file. Any hint on what am I doing wrong? Thanks.

**Comment by kristianmandrup** [comment]
Honestly, I think this gem is a bit outdated. I would advice you to either. Debug and fix as necessary to bring the gem in line with latest Ember and Konacha API and conventions or ...
Use ember-cli and their test recommendations such as Ember tests via Qunit.

**Comment by yortz** [comment]
You are right, I think that the extension needs some minor tweaks to be used with latest ember and ember-data revision, anyway I managed to setup and configure konacha + mocha + chai in my rails/ember app without the use of the gem. I am gonna close this one.
